name: Build guc for USD v24.03

on:
  workflow_call:
    inputs:
      build-config:
        required: true
        type: string
      extra-cmake-flags:
        required: false
        type: string

    outputs:
      archive-name:
        description: "Name of the archive containing the build artifacts."
        value: build-${{ inputs.build-config }}-${{ github.sha }}

jobs:
  build:
    name: Build ${{ matrix.os-family }} ${{ matrix.build-config }}

    strategy:
      matrix:
        include:
        - os-family: Linux
          image: ubuntu-20.04
          usd-download-url: "https://github.com/pablode/USD/releases/download/v24.03-ci-release/USD24.03_Linux_x64_Python3.9.tar.gz"
          usd-install-path: /home/runner/work/USD/USD/INSTALL
          archive-file-name: guc_USD24.03_Linux_x64_Python3.9.tar.gz

        - os-family: MacOS
          image: macos-12
          usd-download-url: "https://github.com/pablode/USD/releases/download/v24.03-ci-release/USD24.03_MacOS_x64_Python3.9.tar.gz"
          usd-install-path: /Users/runner/work/USD/USD/INSTALL
          archive-file-name: guc_USD24.03_MacOS_x64_Python3.9.tar.gz

        - os-family: Windows
          image: windows-2019
          usd-download-url: "https://github.com/pablode/USD/releases/download/v24.03-ci-release/USD24.03_Windows_x64_Python3.9.tar.gz"
          usd-install-path: C:/INSTALL
          archive-file-name: guc_USD24.03_Windows_x64_Python3.9.tar.gz

    uses: ./.github/workflows/build.yml
    with:
      image: ${{ matrix.image }}
      build-config: ${{ inputs.build-config }}
      usd-download-url: ${{ matrix.usd-download-url }}
      usd-install-path: ${{ matrix.usd-install-path }}
      archive-name: build-${{ inputs.build-config }}-${{ github.sha }}
      archive-file-name: ${{ matrix.archive-file-name }}
      extra-cmake-flags: ${{ inputs.extra-cmake-flags }}
