name: Deploy Release

on:
  workflow_dispatch:

jobs:
  build-2403:
    name: Build guc for USD v24.03
    uses: ./.github/workflows/build-usd.yml
    with:
      usd-version: 24.03
      build-config: Release

  build-2311:
    name: Build guc for USD v23.11
    uses: ./.github/workflows/build-usd.yml
    with:
      usd-version: 23.11
      build-config: Release

  deploy-release:
    name: Deploy Release
    needs: [build-2403, build-2311]
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.build.outputs.archive-name }}

      - name: Deploy draft release
        uses: softprops/action-gh-release@d4e8205d7e959a9107da6396278b2f1f07af0f9b
        with:
          name: "Version XXX"
          body: "TBD"
          files: |
            *.tar.gz
          fail_on_unmatched_files: true
          draft: true
