name: Deploy Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  build:
    name: Build guc for USD v24.03
    uses: ./.github/workflows/build-usd.yml
    with:
      usd-version: 24.03
      build-config: Release

  deploy-release:
    name: Deploy Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.build.outputs.archive-name }}

      - name: Deploy draft release
        uses: softprops/action-gh-release@d4e8205d7e959a9107da6396278b2f1f07af0f9b
        with:
          name: "Version XXX"
          body: "TBD"
          files: |
            *.tar.gz
          fail_on_unmatched_files: true
          draft: true
